# https://supabase.com/docs/guides/cli/config
project_id = "chsepsbqkfyakjqrktzy"

[auth]
enabled = true
site_url = "https://tailored-tech-test-gamma.vercel.app"
additional_redirect_urls = [
  "https://tailored-tech-test-gamma.vercel.app",
  "http://localhost:5173",
  "http://127.0.0.1:5173",
]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[auth.rate_limit]
# Requires custom SMTP to take effect above built-in 2/hr.
email_sent = 5
sms_sent = 30
anonymous_users = 30
token_refresh = 150
sign_in_sign_ups = 30
token_verifications = 30
web3 = 30
